# dbt_transformation:
#   outputs:
#     dev:
#       dataset: "{{ env_var('DBT_BIGQUERY_DATASET', '') }}"
#       job_execution_timeout_seconds: 300
#       job_retries: 1
#       keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE_PATH', '') }}"
#       location: "{{ env_var('DBT_BIGQUERY_LOCATION', '') }}"
#       method: service-account
#       priority: interactive
#       project: "{{ env_var('DBT_BIGQUERY_PROJECT', '') }}"
#       threads: 1
#       type: bigquery
#   target: dev


dbt_transformation:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: data-engineering-f2025
      dataset: transformed_dataset
      location: US
      threads: 1
      keyfile: /mnt/c/Users/kaizakunonu/Desktop/DataEngineering/Keys/data-engineering-f2025-airbyte.json